name: pertemuan_14
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+4 # Untuk SQLite
  path_provider: ^2.0.11 # Untuk menentukan lokasi direktori database
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
